[package]
version = "0.1.1"
name = "intelli-api"
edition = "2021"
readme = "README.md"
rust-version = "1.71.0"
description = "F123 Championship Tool"
authors = ["Gpeaky <gerardjoven2020@hotmail.com>"]
license = "MIT"
repository = "https://github.com/GPeaky/intelli-api"

[dependencies]
ahash = "0.8.3"
scylla = "0.9.0"
garde = "0.14.0"
bincode = "1.3.3"
askama = "0.12.0"
dotenvy = "0.15.7"
tracing = "0.1.37"
thiserror = "1.0.44"
serde_trim = "1.0.0"
rust-argon2 = "2.0.0"
jsonwebtoken = "8.3.0"
serde-big-array = "0.5.1"
tracing-subscriber = "0.3.17"
tokio = { version = "1.31.0", features = ["full"] }
chrono = { version = "0.4.26", features = ["serde"] }
serde = { version = "1.0.183", features = ["derive"] }
redis = { version = "0.23.1", features = ["tokio-comp"] }
hyper = { version = "0.14.27", features = ["http2", "full"] }
axum-server = { version = "0.5.1", features = ["tls-rustls"] }
lettre = { version = "0.10.4", default-features = false, features = [
    "tokio1-rustls-tls",
    "smtp-transport",
    "builder",
] }
axum = { version = "0.6.20", features = [
    "form",
    "macros",
    "multipart",
    "headers",
    "http2",
    "ws",
] }
tower = { version = "0.4.13", features = [
    "limit",
    "buffer",
    "tokio",
    "timeout",
] }
tower-http = { version = "0.4.3", features = ["cors"] }
serde_json = "1.0.104"
rmp-serde = "1.1.2"
rand = "0.8.5"

[profile.release]
debug = 0
lto = "fat"
opt-level = 3
codegen-units = 1
split-debuginfo = "off"
# panic = "abort"
