[package]
name = "intelli"
edition = "2021"
version = "0.4.18"
readme = "README.md"
description = "F123 Championship Tool"
authors = ["Gpeaky <gerardjoven2020@hotmail.com>"]
repository = "https://github.com/GPeaky/intelli-api"
license = "MIT"

[build-dependencies]
prost-build = "0.12"

[dependencies]
log = "0.4"
prost = "0.12"
garde = "0.16"
fastrand = "2"
bcrypt = "0.15"
rustc-hash = "1"
sailfish = "0.8"
dotenvy = "0.15"
mimalloc = "0.1"
serde_trim = "1"
ntex-cors = "0.4"
thiserror = "1.0"
serde_derive = "1"
jsonwebtoken = "9"
env_logger = "0.10"
async-trait = "0.1"
deadpool-redis = "0.14"
postgres-derive = "0.4"
zerocopy = "0.8.0-alpha.1"
deadpool-postgres = "0.12.0"
zerocopy-derive = "0.8.0-alpha.1"
serde = { version = "1", features = ["rc"] }
tokio = { version = "1", features = ["full"] }
ntex = { version = "0.7", features = ["tokio"] }
reqwest = { version = "0.11", features = ["json"] }
rkyv = { version = "0.7", features = ["validation"] }
once_cell = { version = "1", features = ["parking_lot"] }
chrono = { version = "0.4", features = ["serde", "rkyv"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }
postgres-types = { version = "0.2", features = ["with-chrono-0_4"] }
parking_lot = { version = "0.12", features = [
    "arc_lock",
    "hardware-lock-elision",
] }
lettre = { version = "0.11", default-features = false, features = [
    "tokio1-rustls-tls",
    "smtp-transport",
    "builder",
] }


[profile.release]
debug = 0
lto = "fat"
opt-level = 3
codegen-units = 1
split-debuginfo = "off"
panic = "abort"
